sonar.projectKey=mazenhassan20_SecOps-Pipeline
sonar.organization=mazenhassan20
sonar.python.version=3
sonar.exclusions=Dockerfile,requirements.txt
sonar.sources=app.py
sonar.tests=test_app.py
sonar.python.coverage.reportPaths=coverage.xml
